language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer update

script:
  # check coding standard for our code
  #- vendor/bin/phpcs -p --standard=psr2 src tests
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - composer require --dev phpstan/phpstan:^0.6 && vendor/bin/phpstan analyse -l 4 src

after_script:
  # get scrutinizer for coverage upload
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
